version: "3.7"

services:
  # PHP-FPM - Service
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: inspiring-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www

    volumes:
      - ./:/var/www
      - ./docker-files/php/local.ini:/usr/local/etc/php/conf.d/local.ini

    networks:
      - inspiring-app-network

  # NGINX - Service
  webserver:
    image: nginx:alpine
    container_name: inspiring-webserver
    restart: unless-stopped
    tty: true

    ports:
      - "8100:80"
      - "8143:443"

    volumes:
      - ./:/var/www
      - ./docker-files/nginx/conf.d/:/etc/nginx/conf.d/

    networks:
      - inspiring-app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: inspiring-db
    restart: unless-stopped
    tty: true
    ports:
      - "3309:3309"
    environment:
      MYSQL_DATABASE: inspiring
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker-files/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - inspiring-app-network

  #Redis Service
  redis:
      image: redis:alpine
      container_name: inspiring-app-redis
      command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
      volumes:
      - ./data/redis:/data
      ports:
        - "8002:6379"
      networks:
        - inspiring-app-network

# Volumes
volumes:
  dbdata:
    driver: local

# Networks
networks:
  inspiring-app-network:
    driver: bridge
